### ISSUE TITLE
What versions of sqlite3 does tuql support?

### ISSUE THREAD

**Issue by barbalex** [bradleyboy/tuql#22]
Because of a different Issue (https://github.com/bradleyboy/tuql/issues/21) I was forced to install a new version of sqlite3, which is now 4.0.1.

I am getting this error:

```
alexa@DESKTOP-6C4V66Q C:\Users\alexa\test-tuql
$ yarn tuql kapla.sqlite --graphiql
yarn run v1.7.0
$ C:\Users\alexa\test-tuql\node_modules\.bin\tuql kapla.sqlite --graphiql

 > Reading schema from database.sqlite
(node:16452) UnhandledPromiseRejectionWarning: Error: Query fields must be an object with field names as keys or a function which returns such an object.
    at invariant (C:\Users\alexa\test-tuql\node_modules\graphql\jsutils\invariant.js:18:11)
    at defineFieldMap (C:\Users\alexa\test-tuql\node_modules\graphql\type\definition.js:353:54)
    at GraphQLObjectType.getFields (C:\Users\alexa\test-tuql\node_modules\graphql\type\definition.js:310:44)
    at typeMapReducer (C:\Users\alexa\test-tuql\node_modules\graphql\type\schema.js:208:25)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (C:\Users\alexa\test-tuql\node_modules\graphql\type\schema.js:97:34)
    at Promise (C:\Users\alexa\test-tuql\node_modules\tuql\dist\builders\schema.js:243:13)
```

Could it be that sqlite3 is only supported in major version 3?
The actual database is in sqlite version 3.22.0.

**Comment by mikeerickson** [comment]
I am having same problem, I am using sqlite3 3.16.0 2016-11-04 version

@barbalex Did you ever get this working?

**Comment by barbalex** [comment]
nope

**Comment by mikeerickson** [comment]
@barbalex Quite a bummer, and no response from author either.  Seems to be kinda quiet

**Comment by barbalex** [comment]
yeah, I am not going to take up the slack as I am only a simple consumer checking out if this could work for me :-|

**Comment by bradleyboy** [comment]
Please let me know if you still have issues with 1.7.0
